### ISSUE TITLE
Missing tutorial/documentation

### ISSUE THREAD

**Issue by merwok** [tianon/gosu#10]
Hello!  This looks interesting but I did not manage to run a simple example like `gosu root who am i`.  How should one configure things?

FTR I don’t have fine-grained sudo-like needs, I’m the only user of my laptop and I’m tired of quoting commands with `su -c`.  (I don’t like sudo for philosophical reasons and don’t use it.)  OTOH I could be interested in fine-grained configuration, for instance to manage developers’ access on deployment machines.

**Comment by tianon** [comment]
The main use-case I was solving when I created `gosu` was that of processes that _are_ root, but don't want to be, not the other way around.  However, if you really want to use this solution for the opposite problem, you _should_ be able to set the binary setuid (`chmod +s gosu`), and then run it as any user.  Beware though that there will be no authentication, and that any command is permitted (with intentionally no configurability, which is why I don't recommend this as a real solution unless you're OK with those glaring issues).

**Comment by merwok** [comment]
Ah! I totally missed that, with the description talking about su and sudo.  I guess I’ll write my own shell function to avoid the damn quoting when using su. :)
