### ISSUE TITLE
How does gosu compare to su-exec?

### ISSUE THREAD

**Issue by qdm12** [tianon/gosu#52]
Hi there,

First thanks for your great utility!

Your repository seems much more maintained and active than su-exec's one. But in the end, what are the advantages of using gosu over su-exec? That would be a great addition to the su-exec part in your readme.

Also, have you tried compressing gosu with UPX? As ram usage is only temporary I think it would be worth compressing it to reduce its size? 

Many thanks.

**Comment by tianon** [comment]
> But in the end, what are the advantages of using gosu over su-exec?

"`go get`" instead of "download, `make`, `make install`"; uses Docker/libcontainer's own user string parsing code (which the `README` currently mentions), but otherwise there aren't any

We've got a test suite here (https://github.com/tianon/gosu/blob/74d8730b0bab611cbf204fd4419ef21ecb6df017/Dockerfile.test) that I've personally run against `su-exec` to verify that it functions as expected, even in all the weird edge cases.

> Also, have you tried compressing gosu with UPX? As ram usage is only temporary I think it would be worth compressing it to reduce its size?

To be honest, I haven't looked at, touched, or even though about UPX since well before https://github.com/golang/go/issues/16706 (at the time I last looked at it, it was causing issues with Go binaries IIRC).  If it works, great, but I don't plan to use it for official releases.  Folks who are concerned about the final binary size (which is already pretty lean at 2MB) should really use `su-exec` or one of the other alternatives like `chroot` instead.
