### ISSUE TITLE
Please consider adding a changelog

### ISSUE THREAD

**Issue by deogracia** [tianon/gosu#53]
Hi!

Thanks for your work :D 

Would my mind considering adding a changelog (like https://keepachangelog.com)?
It's not clear to me, since there is 2 years between 1.10 and 1.11, what change between these two versions.

**Comment by tianon** [comment]
GitHub already provides this -- https://github.com/tianon/gosu/compare/1.10...1.11

That gives a full log of all commits alongside a full diff (which isn't much -- mostly packaging, docs, and adding `--version` / `--help`); see https://github.com/tianon/gosu/compare/1.10...1.11#diff-7ddfb3e035b42cd70649cc33393fe32c for the specific bit that actually has a "meaningful" change.

These days `gosu` is mature enough that IMO there aren't enough changes to warrant bothering with an explicit changelog; to illustrate, see https://github.com/tianon/gosu/compare/1.11...master, which shows all the changes since 1.11 (and there's really not anything substantial there).

I do try to note major changes in the "release notes" on each GitHub release: https://github.com/tianon/gosu/releases (which is maybe more of the high-level summary you're looking for).
