### ISSUE TITLE
I am having some issue with gosu

### ISSUE THREAD

**Issue by quanghnn** [tianon/gosu#63]
I get this error

>  failed switching to "root": operation not permitted

When I use command 

> gosu mysql
or
> gosu root

to edit file in docker-entrypoint.sh

**Comment by tianon** [comment]
This tool is for switching from `root` to *less* privileges -- you want `su` or `sudo`.

**Comment by tianon** [comment]
The correct solution for that use case is `sudo`, configured with `NOPASSWD:` in the configuration.

**Comment by BooleanType** [comment]
@tianon Yes, looks like it works, thanks!

Here is new command in my Dockerfile:

```
RUN echo 'api ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/api && \
    chmod 440 /etc/sudoers.d/api
```

And in my entrypoint file I do this:

```sh
sudo chown -R api:api .
```

... instead of this:

```sh
gosu root:root bash -c 'chown -R api:api .'
```

And my question is:  with this change I allow my `api` user to run commands as `root` without password. Is it _really_ more safe, then using `gosu`, which is installed with the 'setuid' bit set and which switches `api` user to `root`?

**Comment by tianon** [comment]
With that configuration, it's roughly the same (although scoped to JUST your user, not all users), and `sudo` has other protective measures in it for this use case that `gosu` does not. For example, you can now adjust that configuration to ONLY allow `chown`, and lock it down even further.
