### ISSUE TITLE
CVE-2021-29923: go 1.16.7 needs to upgrade to go 1.17.x

### ISSUE THREAD

**Issue by quickwind** [tianon/gosu#91]
https://nvd.nist.gov/vuln/detail/CVE-2021-29923

**Comment by tianon** [comment]
... I'm a little lost.

What does that CVE have to do with `gosu`?

**Comment by quickwind** [comment]
@tianon , we installed the latest 1.14 gosu binary, but our security scan tool reported this CVE on it:

CVE-2021-29923	go	1.16.7	fixed in 1.17	high	7.5	CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N	Go before 1.17 does not properly consider extraneous zero characters at the beginning of an IP address octet, which (in some situations) allows attackers to bypass access control that is based on IP addresses, because of unexpected octal interpretation. This affects net.ParseIP and net.ParseCIDR.	https://nvd.nist.gov/vuln/detail/CVE-2021-29923

**Comment by tianon** [comment]
This tool does not parse IP addresses. This is a false positive in your security scanner, and I would suggest you report it as such to the vendor.

**Comment by quickwind** [comment]
@tianon, ok, but when do we plan to upgrade to go 1.17?

**Comment by tianon** [comment]
Probably when it's had a little more time to bake in other projects? It literally _just_ got released; without a really compelling reason to, it seems a bit premature to upgrade right away "just because" (and "there's a CVE that doesn't affect us at all and the affected code likely doesn't even end up in our compiled binary" is not remotely compelling or interesting -- that's a tool being way too overaggressive).
